/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jnaneshbt
 */
public class gravity extends javax.swing.JPanel {

    private int x_value = 0;
    private int y_value = 0;
    private int z_value = 0;
    private String unit = "";

    /**
     * Creates new form Gravity
     */
    public gravity() {
        initComponents();
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        UpButton = new javax.swing.JButton();
        DownButton = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        xtextArea = new javax.swing.JTextArea();
        label2 = new javax.swing.JLabel();
        ytextArea = new javax.swing.JTextArea();
        label3 = new javax.swing.JLabel();
        ztextArea = new javax.swing.JTextArea();
        label4 = new javax.swing.JLabel();
        xcb = new javax.swing.JCheckBox();
        ycb = new javax.swing.JCheckBox();
        zcb = new javax.swing.JCheckBox();

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        UpButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        UpButton.setText("      UP     ");
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });

        DownButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        DownButton.setText("DOWN");
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("GRAVITY");

        xtextArea.setEditable(false);
        xtextArea.setBackground(new java.awt.Color(0, 153, 204));
        xtextArea.setColumns(20);
        xtextArea.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        xtextArea.setRows(5);
        xtextArea.setText(" ");
        xtextArea.setToolTipText("");

        label2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("X-axis");

        ytextArea.setEditable(false);
        ytextArea.setBackground(new java.awt.Color(0, 153, 204));
        ytextArea.setColumns(20);
        ytextArea.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        ytextArea.setRows(5);
        ytextArea.setText(" ");
        ytextArea.setToolTipText("");

        label3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Z-axis");

        ztextArea.setEditable(false);
        ztextArea.setBackground(new java.awt.Color(0, 153, 204));
        ztextArea.setColumns(20);
        ztextArea.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        ztextArea.setRows(5);
        ztextArea.setText(" ");
        ztextArea.setToolTipText("");

        label4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Y-axis");

        xcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xcbActionPerformed(evt);
            }
        });

        ycb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ycbActionPerformed(evt);
            }
        });

        zcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zcbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UpButton)
                        .addGap(30, 30, 30)
                        .addComponent(DownButton)))
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3)
                        .addGap(18, 18, 18)
                        .addComponent(ztextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label4)
                        .addGap(18, 18, 18)
                        .addComponent(ytextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2)
                        .addGap(18, 18, 18)
                        .addComponent(xtextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(xcb)
                        .addComponent(ycb, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(zcb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(label)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xtextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(xcb)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ytextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ycb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ztextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(zcb)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label3))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed

        if (xcb.isSelected()) {
            x_value++;
        }

        if (ycb.isSelected()) {
            y_value++;
        }

        if (zcb.isSelected()) {
            z_value++;
        }

        update();
    }//GEN-LAST:event_UpButtonActionPerformed

    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
        if (xcb.isSelected()) {
            x_value--;
        }

        if (ycb.isSelected()) {
            y_value--;
        }

        if (zcb.isSelected()) {
            z_value--;
        }

        update();
    }//GEN-LAST:event_DownButtonActionPerformed

    private void xcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xcbActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void ycbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ycbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ycbActionPerformed

    private void zcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zcbActionPerformed

   void publish() {
        String topic = "Gravity";
        String content = "X:"+String.valueOf(x_value) +
                " Y:"+String.valueOf(y_value) +
                " Z:"+String.valueOf(z_value);
                
        config.getPublisher().publish(topic, content);
    }

    
    private void update() {
        xtextArea.setText(String.valueOf(x_value) );
        ytextArea.setText(String.valueOf(y_value) );
        ztextArea.setText(String.valueOf(z_value) );
        publish();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownButton;
    private javax.swing.JButton UpButton;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JCheckBox xcb;
    private javax.swing.JTextArea xtextArea;
    private javax.swing.JCheckBox ycb;
    private javax.swing.JTextArea ytextArea;
    private javax.swing.JCheckBox zcb;
    private javax.swing.JTextArea ztextArea;
    // End of variables declaration//GEN-END:variables
}
