/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlpanel;

import java.awt.Canvas;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author jnaneshbt
 */
public class ui extends javax.swing.JFrame {

    /**
     * Creates new form ui
     */
    public ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ledBulbPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        OFF_ON_BUTTON = new javax.swing.JToggleButton();
        scmPanel = new javax.swing.JPanel();
        breakfastbutton = new javax.swing.JButton();
        receipesbutton = new javax.swing.JButton();
        snacksbutton = new javax.swing.JButton();
        powerbutton = new javax.swing.JButton();
        settingsbutton = new javax.swing.JButton();
        vegchoppingbutton = new javax.swing.JButton();
        newreceipebutton = new javax.swing.JButton();
        autocleanbutton = new javax.swing.JButton();
        doorbutton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        ledbulbbutton = new javax.swing.JButton();
        refrigeratorbutton = new javax.swing.JButton();
        valvebutton = new javax.swing.JButton();
        roomacbutton = new javax.swing.JButton();
        tvbutton = new javax.swing.JButton();
        watertankbutton = new javax.swing.JButton();
        carbutton = new javax.swing.JButton();
        cookingMachine_button = new javax.swing.JButton();
        washingmachinebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IoT Smart Home Control Panel");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 102));
        setResizable(false);

        ledBulbPanel.setBackground(new java.awt.Color(0, 0, 102));

        homeButton.setBackground(new java.awt.Color(255, 0, 153));
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        OFF_ON_BUTTON.setText("ON");
        OFF_ON_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFF_ON_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ledBulbPanelLayout = new javax.swing.GroupLayout(ledBulbPanel);
        ledBulbPanel.setLayout(ledBulbPanelLayout);
        ledBulbPanelLayout.setHorizontalGroup(
            ledBulbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledBulbPanelLayout.createSequentialGroup()
                .addGroup(ledBulbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ledBulbPanelLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(OFF_ON_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ledBulbPanelLayout.setVerticalGroup(
            ledBulbPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ledBulbPanelLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(OFF_ON_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ledBulbPanel.setVisible(false);

        scmPanel.setBackground(new java.awt.Color(0, 0, 153));

        breakfastbutton.setBackground(new java.awt.Color(255, 0, 51));
        breakfastbutton.setText("BREAKFAST");
        breakfastbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastbuttonActionPerformed(evt);
            }
        });

        receipesbutton.setText("RECEIPES");
        receipesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipesbuttonActionPerformed(evt);
            }
        });

        snacksbutton.setText("SNACKS");
        snacksbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snacksbuttonActionPerformed(evt);
            }
        });

        powerbutton.setText("POWER ");
        powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerbuttonActionPerformed(evt);
            }
        });

        settingsbutton.setText("SETTINGS");
        settingsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsbuttonActionPerformed(evt);
            }
        });

        vegchoppingbutton.setText("VEG CHOPPING");
        vegchoppingbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vegchoppingbuttonActionPerformed(evt);
            }
        });

        newreceipebutton.setText("NEW RECEIPE");
        newreceipebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newreceipebuttonActionPerformed(evt);
            }
        });

        autocleanbutton.setText("AUTO CLEAN");
        autocleanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autocleanbuttonActionPerformed(evt);
            }
        });

        doorbutton.setText("DOOR OPEN/CLOSE");
        doorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout scmPanelLayout = new javax.swing.GroupLayout(scmPanel);
        scmPanel.setLayout(scmPanelLayout);
        scmPanelLayout.setHorizontalGroup(
            scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scmPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(scmPanelLayout.createSequentialGroup()
                        .addComponent(vegchoppingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(settingsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(powerbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(scmPanelLayout.createSequentialGroup()
                        .addComponent(breakfastbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(receipesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(snacksbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(scmPanelLayout.createSequentialGroup()
                        .addComponent(newreceipebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(autocleanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(doorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        scmPanelLayout.setVerticalGroup(
            scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scmPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfastbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receipesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snacksbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newreceipebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autocleanbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(scmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vegchoppingbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(powerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        homePanel.setBackground(new java.awt.Color(0, 0, 153));

        ledbulbbutton.setBackground(new java.awt.Color(255, 0, 51));
        ledbulbbutton.setText("LED BULB");
        ledbulbbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ledbulbbuttonActionPerformed(evt);
            }
        });

        refrigeratorbutton.setText("REFRIGERATOR");
        refrigeratorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrigeratorbuttonActionPerformed(evt);
            }
        });

        valvebutton.setText("VALVE");
        valvebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valvebuttonActionPerformed(evt);
            }
        });

        roomacbutton.setText("ROOM AC");
        roomacbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomacbuttonActionPerformed(evt);
            }
        });

        tvbutton.setText("TV");
        tvbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvbuttonActionPerformed(evt);
            }
        });

        watertankbutton.setText("WATER TANK");
        watertankbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watertankbuttonActionPerformed(evt);
            }
        });

        carbutton.setText("CAR");
        carbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbuttonActionPerformed(evt);
            }
        });

        cookingMachine_button.setBackground(new java.awt.Color(255, 0, 0));
        cookingMachine_button.setText("COOKING MACHINE");
        cookingMachine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookingMachine_buttonActionPerformed(evt);
            }
        });

        washingmachinebutton.setText("WASHING MACHINE");
        washingmachinebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingmachinebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(watertankbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(tvbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(roomacbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(ledbulbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(refrigeratorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(valvebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(carbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(cookingMachine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(washingmachinebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ledbulbbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refrigeratorbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valvebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cookingMachine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(washingmachinebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(watertankbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomacbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ledBulbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ledBulbPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        scmPanel.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_powerbuttonActionPerformed

    ledBulbPanel ledb = new ledBulbPanel();
    private void breakfastbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastbuttonActionPerformed
        scmPanel.setVisible(false);
        ledBulbPanel.setVisible(true);
        // Component ledc = add(ledb);
        //ledb.setVisible(true);


    }//GEN-LAST:event_breakfastbuttonActionPerformed

    private void settingsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsbuttonActionPerformed

    private void vegchoppingbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vegchoppingbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vegchoppingbuttonActionPerformed

    private void snacksbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snacksbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snacksbuttonActionPerformed

    private void receipesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipesbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receipesbuttonActionPerformed

    private void newreceipebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newreceipebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newreceipebuttonActionPerformed

    private void autocleanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autocleanbuttonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_autocleanbuttonActionPerformed

    private void doorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doorbuttonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        ledBulbPanel.setVisible(false);
        scmPanel.setVisible(false);
        homePanel.setVisible(true);

    }//GEN-LAST:event_homeButtonActionPerformed

    boolean onFlag = false;
    private void OFF_ON_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFF_ON_BUTTONActionPerformed

        if (onFlag) {
            OFF_ON_BUTTON.setText("OFF");
        } else {
            OFF_ON_BUTTON.setText("ON");
        }

        onFlag = !onFlag;
        String content = "" + onFlag;
        config.getPublisher().publish("bulb", content);

    }//GEN-LAST:event_OFF_ON_BUTTONActionPerformed

    private void ledbulbbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledbulbbuttonActionPerformed
        // TODO add your handling code here:
        ledBulbPanel.setVisible(true);
        homePanel.setVisible(false);
        scmPanel.setVisible(false);


    }//GEN-LAST:event_ledbulbbuttonActionPerformed

    private void refrigeratorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrigeratorbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrigeratorbuttonActionPerformed

    private void valvebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valvebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valvebuttonActionPerformed

    private void roomacbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomacbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomacbuttonActionPerformed

    private void tvbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvbuttonActionPerformed

    private void watertankbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watertankbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watertankbuttonActionPerformed

    private void carbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carbuttonActionPerformed

    private void cookingMachine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookingMachine_buttonActionPerformed
        ledBulbPanel.setVisible(false);
        homePanel.setVisible(false);
        scmPanel.setVisible(true);

    }//GEN-LAST:event_cookingMachine_buttonActionPerformed

    private void washingmachinebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingmachinebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washingmachinebuttonActionPerformed

    public static void startui() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ui().setVisible(true);
        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        startui();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton OFF_ON_BUTTON;
    private javax.swing.JButton autocleanbutton;
    private javax.swing.JButton breakfastbutton;
    private javax.swing.JButton carbutton;
    private javax.swing.JButton cookingMachine_button;
    private javax.swing.JButton doorbutton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel ledBulbPanel;
    private javax.swing.JButton ledbulbbutton;
    private javax.swing.JButton newreceipebutton;
    private javax.swing.JButton powerbutton;
    private javax.swing.JButton receipesbutton;
    private javax.swing.JButton refrigeratorbutton;
    private javax.swing.JButton roomacbutton;
    private javax.swing.JPanel scmPanel;
    private javax.swing.JButton settingsbutton;
    private javax.swing.JButton snacksbutton;
    private javax.swing.JButton tvbutton;
    private javax.swing.JButton valvebutton;
    private javax.swing.JButton vegchoppingbutton;
    private javax.swing.JButton washingmachinebutton;
    private javax.swing.JButton watertankbutton;
    // End of variables declaration//GEN-END:variables
}
